name: Build Whisper Vulkan (choco\Windows)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-2022 # safer until 2025 migration is stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.28.3'

      - name: Install Vulkan SDK (latest)
        shell: pwsh
        run: |
          # Get the latest Vulkan SDK version dynamically
          $latestUrl = "https://vulkan.lunarg.com/sdk/latest/windows.txt"
          $latestVersion = (Invoke-WebRequest -Uri $latestUrl -UseBasicParsing).Content.Trim()
          Write-Host "Latest Vulkan SDK version: $latestVersion"

          $installerUrl = "https://sdk.lunarg.com/sdk/download/$latestVersion/windows/VulkanSDK-$latestVersion-Installer.exe"
          Invoke-WebRequest -Uri $installerUrl -OutFile vulkan-sdk.exe

          # Silent install
          Start-Process ".\vulkan-sdk.exe" -ArgumentList "/S" -Wait

          # Set environment variables
          $vulkanPath = "C:\VulkanSDK\$latestVersion"
          echo "VULKAN_SDK=$vulkanPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          echo "$vulkanPath\Bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
          echo "$vulkanPath\Lib" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Configure CMake
        run: cmake -S . -B build -A x64 -DWHISPER_VULKAN=ON

      - name: Build
        run: cmake --build build --config Release
