# .github/workflows/build-vulkan.yml
name: Build Whisper Vulkan (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@v2

      - name: Install Vulkan SDK (latest)
        shell: pwsh
        run: |
          # Fetch the latest version
          $latestVersion = (Invoke-WebRequest -Uri "https://vulkan.lunarg.com/sdk/latest/windows.txt" -UseBasicParsing).Content.Trim()
          Write-Host "Latest Vulkan SDK version: $latestVersion"

          # Use correct filename format
          $installerUrl = "https://sdk.lunarg.com/sdk/download/$latestVersion/windows/vulkansdk-windows-X64-$latestVersion.exe"
          Write-Host "Downloading Vulkan SDK installer from: $installerUrl"

          # Download and install silently
          Invoke-WebRequest -Uri $installerUrl -OutFile vulkansdk.exe -ErrorAction Stop
          Start-Process ".\vulkansdk.exe" -ArgumentList "/S" -Wait

          # Set environment
          $vulkanPath = "C:\VulkanSDK\$latestVersion"
          if (-Not (Test-Path $vulkanPath)) {
            Write-Error "Vulkan SDK did not install at expected path: $vulkanPath"
            exit 1
          }
          Write-Host "Using VULKAN_SDK=$vulkanPath"
          echo "VULKAN_SDK=$vulkanPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          echo "$vulkanPath\Bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Configure CMake (with Vulkan)
        run: cmake -B build -S . -DGGML_VULKAN=ON -DCMAKE_BUILD_TYPE=Release

      - name: Build Release
        run: cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: whisper-vulkan-windows
          path: build/**

